kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: websocket-test
spec:
    host: websocketstest.127.0.0.1.nip.io
    targetPendingRequests: 20
    scaleTargetRef:
        deployment: websockets-test
        service: websockets-test
        port: 80
    replicas:
        min: 0
        max: 1
