apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "statsmodel-holt"
spec:
  predictor:
    model:
      args: ["--enable_docs_url=True"]
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/statsmodel"