py_dependencies:
	python -m pip install -r requirements-dev.txt
pytest:
	pytest algorithms/ --cov-report term --cov-report=xml:algorithm_coverage.out --cov-report=html:.algorithm_coverage --cov=algorithms/

