apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "linear-regression-model"
  namespace: kserve-test
  labels:
    version: v1
spec:
  predictor:
    minReplicas: 0
    maxReplicas: 4
    scaleTarget: 5
    scaleMetric: rps
    containers:
    - image: localhost:5001/linear_regression_model:x01
      name: kserve-container
      readinessProbe:
        failureThreshold: 5
        initialDelaySeconds: 3
        periodSeconds: 5
        httpGet:
          path: /v1/models/linear_regression_model
          port: 8080
          scheme: HTTP
